baseURL = 'https://cxyclone.github.io/'
defaultContentLanguage = 'zh'
languageCode = 'zh'
title = 'CXYCLONE的笔记'
theme = 'hugo-book'
caches.images.dir = ':cacheDir/images'
copyright = '© 2025 [CXYCLONE](https://github.com/cxyclone)'
disableKinds = ['taxonomy']
disablePathToLower = true


[params]
  BookTheme = 'dark'
  BookSection = '*'
  BookSearch = false
  BookComments = false


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete] 
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
      [markup.goldmark.extensions.typographer]
        disable = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = true
    style = 'base16-snazzy'